# Generated by Django 3.0.7 on 2020-07-18 00:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='groupss', to=settings.AUTH_USER_MODEL),
        ),
    ]
