# Generated by Django 3.0.7 on 2020-07-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_on_cinema',
            field=models.BooleanField(default=True),
        ),
    ]
